// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.hathor_ct_crypto

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_hathor_ct_crypto_mobile_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_hathor_ct_crypto_mobile_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "hathor_ct_crypto_mobile"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}
























































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "hathor_ct_crypto")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
        
    }

    fun uniffi_hathor_ct_crypto_mobile_fn_func_compute_balancing_blinding_factor_uniffi(`value`: Long,`generatorBlindingFactor`: RustBuffer.ByValue,`inputs`: RustBuffer.ByValue,`otherOutputs`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_hathor_ct_crypto_mobile_fn_func_create_asset_commitment_uniffi(`tag`: RustBuffer.ByValue,`blindingFactor`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_hathor_ct_crypto_mobile_fn_func_create_commitment_uniffi(`value`: Long,`blindingFactor`: RustBuffer.ByValue,`generator`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_hathor_ct_crypto_mobile_fn_func_create_shielded_output_uniffi(`value`: Long,`recipientPubkey`: RustBuffer.ByValue,`tokenUid`: RustBuffer.ByValue,`fullyShielded`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_hathor_ct_crypto_mobile_fn_func_create_shielded_output_with_blinding_uniffi(`value`: Long,`recipientPubkey`: RustBuffer.ByValue,`tokenUid`: RustBuffer.ByValue,`fullyShielded`: Byte,`blindingFactor`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_hathor_ct_crypto_mobile_fn_func_create_shielded_output_with_both_blindings_uniffi(`value`: Long,`recipientPubkey`: RustBuffer.ByValue,`tokenUid`: RustBuffer.ByValue,`valueBlindingFactor`: RustBuffer.ByValue,`assetBlindingFactor`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_hathor_ct_crypto_mobile_fn_func_create_surjection_proof_uniffi(`codomainTag`: RustBuffer.ByValue,`codomainBlindingFactor`: RustBuffer.ByValue,`domain`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_hathor_ct_crypto_mobile_fn_func_decrypt_shielded_output_uniffi(`recipientPrivkey`: RustBuffer.ByValue,`ephemeralPubkey`: RustBuffer.ByValue,`commitment`: RustBuffer.ByValue,`rangeProof`: RustBuffer.ByValue,`tokenUid`: RustBuffer.ByValue,`assetCommitment`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_hathor_ct_crypto_mobile_fn_func_derive_asset_tag_uniffi(`tokenUid`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_hathor_ct_crypto_mobile_fn_func_derive_ecdh_shared_secret_uniffi(`privkey`: RustBuffer.ByValue,`pubkey`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_hathor_ct_crypto_mobile_fn_func_derive_rewind_nonce_uniffi(`sharedSecret`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_hathor_ct_crypto_mobile_fn_func_derive_tag_uniffi(`tokenUid`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_hathor_ct_crypto_mobile_fn_func_generate_random_blinding_factor_uniffi(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_hathor_ct_crypto_mobile_fn_func_get_zero_tweak_uniffi(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_hathor_ct_crypto_mobile_fn_func_htr_asset_tag_uniffi(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_hathor_ct_crypto_mobile_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_hathor_ct_crypto_mobile_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_hathor_ct_crypto_mobile_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_hathor_ct_crypto_mobile_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_hathor_ct_crypto_mobile_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_hathor_ct_crypto_mobile_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_hathor_ct_crypto_mobile_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_hathor_ct_crypto_mobile_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_hathor_ct_crypto_mobile_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_hathor_ct_crypto_mobile_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_hathor_ct_crypto_mobile_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_hathor_ct_crypto_mobile_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_hathor_ct_crypto_mobile_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_hathor_ct_crypto_mobile_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_hathor_ct_crypto_mobile_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_hathor_ct_crypto_mobile_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_hathor_ct_crypto_mobile_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_hathor_ct_crypto_mobile_checksum_func_compute_balancing_blinding_factor_uniffi(
    ): Short
    fun uniffi_hathor_ct_crypto_mobile_checksum_func_create_asset_commitment_uniffi(
    ): Short
    fun uniffi_hathor_ct_crypto_mobile_checksum_func_create_commitment_uniffi(
    ): Short
    fun uniffi_hathor_ct_crypto_mobile_checksum_func_create_shielded_output_uniffi(
    ): Short
    fun uniffi_hathor_ct_crypto_mobile_checksum_func_create_shielded_output_with_blinding_uniffi(
    ): Short
    fun uniffi_hathor_ct_crypto_mobile_checksum_func_create_shielded_output_with_both_blindings_uniffi(
    ): Short
    fun uniffi_hathor_ct_crypto_mobile_checksum_func_create_surjection_proof_uniffi(
    ): Short
    fun uniffi_hathor_ct_crypto_mobile_checksum_func_decrypt_shielded_output_uniffi(
    ): Short
    fun uniffi_hathor_ct_crypto_mobile_checksum_func_derive_asset_tag_uniffi(
    ): Short
    fun uniffi_hathor_ct_crypto_mobile_checksum_func_derive_ecdh_shared_secret_uniffi(
    ): Short
    fun uniffi_hathor_ct_crypto_mobile_checksum_func_derive_rewind_nonce_uniffi(
    ): Short
    fun uniffi_hathor_ct_crypto_mobile_checksum_func_derive_tag_uniffi(
    ): Short
    fun uniffi_hathor_ct_crypto_mobile_checksum_func_generate_random_blinding_factor_uniffi(
    ): Short
    fun uniffi_hathor_ct_crypto_mobile_checksum_func_get_zero_tweak_uniffi(
    ): Short
    fun uniffi_hathor_ct_crypto_mobile_checksum_func_htr_asset_tag_uniffi(
    ): Short
    fun ffi_hathor_ct_crypto_mobile_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_hathor_ct_crypto_mobile_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_hathor_ct_crypto_mobile_checksum_func_compute_balancing_blinding_factor_uniffi() != 8749.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_hathor_ct_crypto_mobile_checksum_func_create_asset_commitment_uniffi() != 10504.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_hathor_ct_crypto_mobile_checksum_func_create_commitment_uniffi() != 60745.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_hathor_ct_crypto_mobile_checksum_func_create_shielded_output_uniffi() != 39686.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_hathor_ct_crypto_mobile_checksum_func_create_shielded_output_with_blinding_uniffi() != 22572.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_hathor_ct_crypto_mobile_checksum_func_create_shielded_output_with_both_blindings_uniffi() != 37521.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_hathor_ct_crypto_mobile_checksum_func_create_surjection_proof_uniffi() != 63569.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_hathor_ct_crypto_mobile_checksum_func_decrypt_shielded_output_uniffi() != 24251.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_hathor_ct_crypto_mobile_checksum_func_derive_asset_tag_uniffi() != 7257.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_hathor_ct_crypto_mobile_checksum_func_derive_ecdh_shared_secret_uniffi() != 36587.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_hathor_ct_crypto_mobile_checksum_func_derive_rewind_nonce_uniffi() != 49105.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_hathor_ct_crypto_mobile_checksum_func_derive_tag_uniffi() != 3544.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_hathor_ct_crypto_mobile_checksum_func_generate_random_blinding_factor_uniffi() != 44678.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_hathor_ct_crypto_mobile_checksum_func_get_zero_tweak_uniffi() != 41719.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_hathor_ct_crypto_mobile_checksum_func_htr_asset_tag_uniffi() != 41092.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}



data class BlindingEntry (
    var `value`: kotlin.ULong, 
    var `valueBlindingFactor`: kotlin.ByteArray, 
    var `generatorBlindingFactor`: kotlin.ByteArray
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeBlindingEntry: FfiConverterRustBuffer<BlindingEntry> {
    override fun read(buf: ByteBuffer): BlindingEntry {
        return BlindingEntry(
            FfiConverterULong.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: BlindingEntry) = (
            FfiConverterULong.allocationSize(value.`value`) +
            FfiConverterByteArray.allocationSize(value.`valueBlindingFactor`) +
            FfiConverterByteArray.allocationSize(value.`generatorBlindingFactor`)
    )

    override fun write(value: BlindingEntry, buf: ByteBuffer) {
            FfiConverterULong.write(value.`value`, buf)
            FfiConverterByteArray.write(value.`valueBlindingFactor`, buf)
            FfiConverterByteArray.write(value.`generatorBlindingFactor`, buf)
    }
}



data class CreatedShieldedOutput (
    var `ephemeralPubkey`: kotlin.ByteArray, 
    var `commitment`: kotlin.ByteArray, 
    var `rangeProof`: kotlin.ByteArray, 
    var `blindingFactor`: kotlin.ByteArray, 
    var `assetCommitment`: kotlin.ByteArray?, 
    var `assetBlindingFactor`: kotlin.ByteArray?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeCreatedShieldedOutput: FfiConverterRustBuffer<CreatedShieldedOutput> {
    override fun read(buf: ByteBuffer): CreatedShieldedOutput {
        return CreatedShieldedOutput(
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterOptionalByteArray.read(buf),
            FfiConverterOptionalByteArray.read(buf),
        )
    }

    override fun allocationSize(value: CreatedShieldedOutput) = (
            FfiConverterByteArray.allocationSize(value.`ephemeralPubkey`) +
            FfiConverterByteArray.allocationSize(value.`commitment`) +
            FfiConverterByteArray.allocationSize(value.`rangeProof`) +
            FfiConverterByteArray.allocationSize(value.`blindingFactor`) +
            FfiConverterOptionalByteArray.allocationSize(value.`assetCommitment`) +
            FfiConverterOptionalByteArray.allocationSize(value.`assetBlindingFactor`)
    )

    override fun write(value: CreatedShieldedOutput, buf: ByteBuffer) {
            FfiConverterByteArray.write(value.`ephemeralPubkey`, buf)
            FfiConverterByteArray.write(value.`commitment`, buf)
            FfiConverterByteArray.write(value.`rangeProof`, buf)
            FfiConverterByteArray.write(value.`blindingFactor`, buf)
            FfiConverterOptionalByteArray.write(value.`assetCommitment`, buf)
            FfiConverterOptionalByteArray.write(value.`assetBlindingFactor`, buf)
    }
}



data class DecryptedShieldedOutput (
    var `value`: kotlin.ULong, 
    var `blindingFactor`: kotlin.ByteArray, 
    var `tokenUid`: kotlin.ByteArray, 
    var `assetBlindingFactor`: kotlin.ByteArray?, 
    var `outputType`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeDecryptedShieldedOutput: FfiConverterRustBuffer<DecryptedShieldedOutput> {
    override fun read(buf: ByteBuffer): DecryptedShieldedOutput {
        return DecryptedShieldedOutput(
            FfiConverterULong.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterOptionalByteArray.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: DecryptedShieldedOutput) = (
            FfiConverterULong.allocationSize(value.`value`) +
            FfiConverterByteArray.allocationSize(value.`blindingFactor`) +
            FfiConverterByteArray.allocationSize(value.`tokenUid`) +
            FfiConverterOptionalByteArray.allocationSize(value.`assetBlindingFactor`) +
            FfiConverterString.allocationSize(value.`outputType`)
    )

    override fun write(value: DecryptedShieldedOutput, buf: ByteBuffer) {
            FfiConverterULong.write(value.`value`, buf)
            FfiConverterByteArray.write(value.`blindingFactor`, buf)
            FfiConverterByteArray.write(value.`tokenUid`, buf)
            FfiConverterOptionalByteArray.write(value.`assetBlindingFactor`, buf)
            FfiConverterString.write(value.`outputType`, buf)
    }
}



data class RewindResult (
    var `value`: kotlin.ULong, 
    var `blindingFactor`: kotlin.ByteArray, 
    var `message`: kotlin.ByteArray
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeRewindResult: FfiConverterRustBuffer<RewindResult> {
    override fun read(buf: ByteBuffer): RewindResult {
        return RewindResult(
            FfiConverterULong.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: RewindResult) = (
            FfiConverterULong.allocationSize(value.`value`) +
            FfiConverterByteArray.allocationSize(value.`blindingFactor`) +
            FfiConverterByteArray.allocationSize(value.`message`)
    )

    override fun write(value: RewindResult, buf: ByteBuffer) {
            FfiConverterULong.write(value.`value`, buf)
            FfiConverterByteArray.write(value.`blindingFactor`, buf)
            FfiConverterByteArray.write(value.`message`, buf)
    }
}



data class SurjectionDomainEntry (
    var `generator`: kotlin.ByteArray, 
    var `tag`: kotlin.ByteArray, 
    var `blindingFactor`: kotlin.ByteArray
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSurjectionDomainEntry: FfiConverterRustBuffer<SurjectionDomainEntry> {
    override fun read(buf: ByteBuffer): SurjectionDomainEntry {
        return SurjectionDomainEntry(
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: SurjectionDomainEntry) = (
            FfiConverterByteArray.allocationSize(value.`generator`) +
            FfiConverterByteArray.allocationSize(value.`tag`) +
            FfiConverterByteArray.allocationSize(value.`blindingFactor`)
    )

    override fun write(value: SurjectionDomainEntry, buf: ByteBuffer) {
            FfiConverterByteArray.write(value.`generator`, buf)
            FfiConverterByteArray.write(value.`tag`, buf)
            FfiConverterByteArray.write(value.`blindingFactor`, buf)
    }
}





sealed class CryptoException: kotlin.Exception() {
    
    class InvalidInput(
        
        val `msg`: kotlin.String
        ) : CryptoException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class CryptoFailed(
        
        val `msg`: kotlin.String
        ) : CryptoException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<CryptoException> {
        override fun lift(error_buf: RustBuffer.ByValue): CryptoException = FfiConverterTypeCryptoError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeCryptoError : FfiConverterRustBuffer<CryptoException> {
    override fun read(buf: ByteBuffer): CryptoException {
        

        return when(buf.getInt()) {
            1 -> CryptoException.InvalidInput(
                FfiConverterString.read(buf),
                )
            2 -> CryptoException.CryptoFailed(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: CryptoException): ULong {
        return when(value) {
            is CryptoException.InvalidInput -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is CryptoException.CryptoFailed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
        }
    }

    override fun write(value: CryptoException, buf: ByteBuffer) {
        when(value) {
            is CryptoException.InvalidInput -> {
                buf.putInt(1)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is CryptoException.CryptoFailed -> {
                buf.putInt(2)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalByteArray: FfiConverterRustBuffer<kotlin.ByteArray?> {
    override fun read(buf: ByteBuffer): kotlin.ByteArray? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterByteArray.read(buf)
    }

    override fun allocationSize(value: kotlin.ByteArray?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterByteArray.allocationSize(value)
        }
    }

    override fun write(value: kotlin.ByteArray?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterByteArray.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeBlindingEntry: FfiConverterRustBuffer<List<BlindingEntry>> {
    override fun read(buf: ByteBuffer): List<BlindingEntry> {
        val len = buf.getInt()
        return List<BlindingEntry>(len) {
            FfiConverterTypeBlindingEntry.read(buf)
        }
    }

    override fun allocationSize(value: List<BlindingEntry>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeBlindingEntry.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<BlindingEntry>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeBlindingEntry.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeSurjectionDomainEntry: FfiConverterRustBuffer<List<SurjectionDomainEntry>> {
    override fun read(buf: ByteBuffer): List<SurjectionDomainEntry> {
        val len = buf.getInt()
        return List<SurjectionDomainEntry>(len) {
            FfiConverterTypeSurjectionDomainEntry.read(buf)
        }
    }

    override fun allocationSize(value: List<SurjectionDomainEntry>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeSurjectionDomainEntry.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<SurjectionDomainEntry>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeSurjectionDomainEntry.write(it, buf)
        }
    }
}
    @Throws(CryptoException::class) fun `computeBalancingBlindingFactorUniffi`(`value`: kotlin.ULong, `generatorBlindingFactor`: kotlin.ByteArray, `inputs`: List<BlindingEntry>, `otherOutputs`: List<BlindingEntry>): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_hathor_ct_crypto_mobile_fn_func_compute_balancing_blinding_factor_uniffi(
        FfiConverterULong.lower(`value`),FfiConverterByteArray.lower(`generatorBlindingFactor`),FfiConverterSequenceTypeBlindingEntry.lower(`inputs`),FfiConverterSequenceTypeBlindingEntry.lower(`otherOutputs`),_status)
}
    )
    }
    

    @Throws(CryptoException::class) fun `createAssetCommitmentUniffi`(`tag`: kotlin.ByteArray, `blindingFactor`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_hathor_ct_crypto_mobile_fn_func_create_asset_commitment_uniffi(
        FfiConverterByteArray.lower(`tag`),FfiConverterByteArray.lower(`blindingFactor`),_status)
}
    )
    }
    

        /**
         * Build a 33-byte Pedersen commitment `value * generator + blinding_factor * G`.
         *
         * Mirrors `napi_bindings::create_commitment`. Required by the abstract
         * shielded crypto provider's composed `openAmountShieldedCommitment` /
         * `openFullShieldedCommitment` methods — mobile would otherwise be
         * unable to verify cleartext openings against on-chain commitments.
         */
    @Throws(CryptoException::class) fun `createCommitmentUniffi`(`value`: kotlin.ULong, `blindingFactor`: kotlin.ByteArray, `generator`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_hathor_ct_crypto_mobile_fn_func_create_commitment_uniffi(
        FfiConverterULong.lower(`value`),FfiConverterByteArray.lower(`blindingFactor`),FfiConverterByteArray.lower(`generator`),_status)
}
    )
    }
    

    @Throws(CryptoException::class) fun `createShieldedOutputUniffi`(`value`: kotlin.ULong, `recipientPubkey`: kotlin.ByteArray, `tokenUid`: kotlin.ByteArray, `fullyShielded`: kotlin.Boolean): CreatedShieldedOutput {
            return FfiConverterTypeCreatedShieldedOutput.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_hathor_ct_crypto_mobile_fn_func_create_shielded_output_uniffi(
        FfiConverterULong.lower(`value`),FfiConverterByteArray.lower(`recipientPubkey`),FfiConverterByteArray.lower(`tokenUid`),FfiConverterBoolean.lower(`fullyShielded`),_status)
}
    )
    }
    

    @Throws(CryptoException::class) fun `createShieldedOutputWithBlindingUniffi`(`value`: kotlin.ULong, `recipientPubkey`: kotlin.ByteArray, `tokenUid`: kotlin.ByteArray, `fullyShielded`: kotlin.Boolean, `blindingFactor`: kotlin.ByteArray): CreatedShieldedOutput {
            return FfiConverterTypeCreatedShieldedOutput.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_hathor_ct_crypto_mobile_fn_func_create_shielded_output_with_blinding_uniffi(
        FfiConverterULong.lower(`value`),FfiConverterByteArray.lower(`recipientPubkey`),FfiConverterByteArray.lower(`tokenUid`),FfiConverterBoolean.lower(`fullyShielded`),FfiConverterByteArray.lower(`blindingFactor`),_status)
}
    )
    }
    

    @Throws(CryptoException::class) fun `createShieldedOutputWithBothBlindingsUniffi`(`value`: kotlin.ULong, `recipientPubkey`: kotlin.ByteArray, `tokenUid`: kotlin.ByteArray, `valueBlindingFactor`: kotlin.ByteArray, `assetBlindingFactor`: kotlin.ByteArray): CreatedShieldedOutput {
            return FfiConverterTypeCreatedShieldedOutput.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_hathor_ct_crypto_mobile_fn_func_create_shielded_output_with_both_blindings_uniffi(
        FfiConverterULong.lower(`value`),FfiConverterByteArray.lower(`recipientPubkey`),FfiConverterByteArray.lower(`tokenUid`),FfiConverterByteArray.lower(`valueBlindingFactor`),FfiConverterByteArray.lower(`assetBlindingFactor`),_status)
}
    )
    }
    

    @Throws(CryptoException::class) fun `createSurjectionProofUniffi`(`codomainTag`: kotlin.ByteArray, `codomainBlindingFactor`: kotlin.ByteArray, `domain`: List<SurjectionDomainEntry>): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_hathor_ct_crypto_mobile_fn_func_create_surjection_proof_uniffi(
        FfiConverterByteArray.lower(`codomainTag`),FfiConverterByteArray.lower(`codomainBlindingFactor`),FfiConverterSequenceTypeSurjectionDomainEntry.lower(`domain`),_status)
}
    )
    }
    

    @Throws(CryptoException::class) fun `decryptShieldedOutputUniffi`(`recipientPrivkey`: kotlin.ByteArray, `ephemeralPubkey`: kotlin.ByteArray, `commitment`: kotlin.ByteArray, `rangeProof`: kotlin.ByteArray, `tokenUid`: kotlin.ByteArray?, `assetCommitment`: kotlin.ByteArray?): DecryptedShieldedOutput {
            return FfiConverterTypeDecryptedShieldedOutput.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_hathor_ct_crypto_mobile_fn_func_decrypt_shielded_output_uniffi(
        FfiConverterByteArray.lower(`recipientPrivkey`),FfiConverterByteArray.lower(`ephemeralPubkey`),FfiConverterByteArray.lower(`commitment`),FfiConverterByteArray.lower(`rangeProof`),FfiConverterOptionalByteArray.lower(`tokenUid`),FfiConverterOptionalByteArray.lower(`assetCommitment`),_status)
}
    )
    }
    

    @Throws(CryptoException::class) fun `deriveAssetTagUniffi`(`tokenUid`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_hathor_ct_crypto_mobile_fn_func_derive_asset_tag_uniffi(
        FfiConverterByteArray.lower(`tokenUid`),_status)
}
    )
    }
    

    @Throws(CryptoException::class) fun `deriveEcdhSharedSecretUniffi`(`privkey`: kotlin.ByteArray, `pubkey`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_hathor_ct_crypto_mobile_fn_func_derive_ecdh_shared_secret_uniffi(
        FfiConverterByteArray.lower(`privkey`),FfiConverterByteArray.lower(`pubkey`),_status)
}
    )
    }
    

    @Throws(CryptoException::class) fun `deriveRewindNonceUniffi`(`sharedSecret`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_hathor_ct_crypto_mobile_fn_func_derive_rewind_nonce_uniffi(
        FfiConverterByteArray.lower(`sharedSecret`),_status)
}
    )
    }
    

    @Throws(CryptoException::class) fun `deriveTagUniffi`(`tokenUid`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_hathor_ct_crypto_mobile_fn_func_derive_tag_uniffi(
        FfiConverterByteArray.lower(`tokenUid`),_status)
}
    )
    }
    

        /**
         * Generate a random 32-byte blinding factor (valid secp256k1 scalar).
         *
         * Mirrors `napi_bindings::generate_random_blinding_factor`. Exposed via
         * UniFFI so the mobile RN bridge (and any future UniFFI consumer) can
         * call a dedicated RNG primitive — without this, mobile had to call
         * `create_shielded_output_uniffi` with dummy inputs and extract the
         * blinding factor from the unused result. That workaround is removed
         * once mobile picks up this new export.
         */ fun `generateRandomBlindingFactorUniffi`(): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_hathor_ct_crypto_mobile_fn_func_generate_random_blinding_factor_uniffi(
        _status)
}
    )
    }
    
 fun `getZeroTweakUniffi`(): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_hathor_ct_crypto_mobile_fn_func_get_zero_tweak_uniffi(
        _status)
}
    )
    }
    
 fun `htrAssetTagUniffi`(): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_hathor_ct_crypto_mobile_fn_func_htr_asset_tag_uniffi(
        _status)
}
    )
    }
    


