/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface BlindingEntry {
  value: bigint
  valueBlindingFactor: Buffer
  generatorBlindingFactor: Buffer
}

/** Compute the balancing blinding factor for the last output. */
export declare function computeBalancingBlindingFactor(value: bigint, generatorBlindingFactor: Buffer, inputs: Array<BlindingEntry>, otherOutputs: Array<BlindingEntry>): Buffer

/**
 * Create an AmountShielded output (amount hidden, token visible).
 *
 * Uses `derive_asset_tag(token_uid)` as the unblinded generator.
 */
export declare function createAmountShieldedOutput(value: bigint, recipientPubkey: Buffer, tokenUid: Buffer, valueBlindingFactor: Buffer): CreatedAmountShieldedOutput

/** Create a blinded asset commitment (Generator) from a Tag and blinding factor. */
export declare function createAssetCommitment(tagBytes: Buffer, rAsset: Buffer): Buffer

/** Create a Pedersen commitment. */
export declare function createCommitment(amount: bigint, blinding: Buffer, generator: Buffer): Buffer

/** Result of creating an AmountShielded output (amount hidden, token visible). */
export interface CreatedAmountShieldedOutput {
  ephemeralPubkey: Buffer
  commitment: Buffer
  rangeProof: Buffer
  blindingFactor: Buffer
}

export interface CreatedShieldedOutput {
  ephemeralPubkey: Buffer
  commitment: Buffer
  rangeProof: Buffer
  blindingFactor: Buffer
  assetCommitment?: Buffer
  assetBlindingFactor?: Buffer
}

/** Create a Borromean range proof. */
export declare function createRangeProof(amount: bigint, blinding: Buffer, commitment: Buffer, generator: Buffer, message?: Buffer | undefined | null, nonce?: Buffer | undefined | null): Buffer

/**
 * Create a FullShielded output with both value blinding factor and asset blinding factor
 * provided externally. This is needed for the last output in a FullShielded transaction
 * where the balance equation requires pre-computing the vbf using a known abf.
 */
export declare function createShieldedOutputWithBothBlindings(value: bigint, recipientPubkey: Buffer, tokenUid: Buffer, valueBlindingFactor: Buffer, assetBlindingFactor: Buffer): CreatedShieldedOutput

/** Create a surjection proof. */
export declare function createSurjectionProof(codomainTag: Buffer, codomainBlindingFactor: Buffer, domain: Array<SurjectionDomainEntry>): Buffer

/** Create a trivial (zero-blinding) Pedersen commitment. */
export declare function createTrivialCommitment(amount: bigint, generator: Buffer): Buffer

/** Derive a deterministic NUMS generator for a token UID. */
export declare function deriveAssetTag(tokenUid: Buffer): Buffer

/**
 * Compute ECDH shared secret: SHA256(version_byte || x_coordinate).
 *
 * Uses libsecp256k1's standard ECDH derivation.
 * Returns 32-byte shared secret.
 */
export declare function deriveEcdhSharedSecret(privateKey: Buffer, peerPubkey: Buffer): Buffer

/**
 * Derive a deterministic nonce from a shared secret.
 *
 * nonce = SHA256("Hathor_CT_nonce_v1" || shared_secret)
 * Returns 32-byte nonce suitable for use as a range proof nonce key.
 */
export declare function deriveRewindNonce(sharedSecret: Buffer): Buffer

/** Derive a raw Tag from token UID (for surjection proofs). */
export declare function deriveTag(tokenUid: Buffer): Buffer

/**
 * Generate a fresh ephemeral secp256k1 key pair.
 *
 * Returns (private_key_bytes: 32B, compressed_pubkey_bytes: 33B).
 */
export interface EphemeralKeypair {
  privateKey: Buffer
  publicKey: Buffer
}

export declare function generateEphemeralKeypair(): EphemeralKeypair

/** Generate a random 32-byte blinding factor (valid secp256k1 scalar). */
export declare function generateRandomBlindingFactor(): Buffer

/** Size of a serialized Pedersen commitment. */
export declare function getCommitmentSize(): number

/** Size of a serialized generator. */
export declare function getGeneratorSize(): number

/** The zero tweak (32 zero bytes). */
export declare function getZeroTweak(): Buffer

/** Return the HTR asset tag (token_uid = [0; 32]). */
export declare function htrAssetTag(): Buffer

/** Rewind an AmountShielded output to recover value and blinding factor. */
export declare function rewindAmountShieldedOutput(privateKey: Buffer, ephemeralPubkey: Buffer, commitment: Buffer, rangeProof: Buffer, tokenUid: Buffer): RewoundAmountShieldedOutput

/** Rewind a FullShielded output to recover value, blinding factor, token UID and asset blinding. */
export declare function rewindFullShieldedOutput(privateKey: Buffer, ephemeralPubkey: Buffer, commitment: Buffer, rangeProof: Buffer, assetCommitment: Buffer): RewoundFullShieldedOutput

export declare function rewindRangeProof(proof: Buffer, commitment: Buffer, nonce: Buffer, generator: Buffer): RewindResult

/** Rewind a Borromean range proof to recover the committed value, blinding factor, and message. */
export interface RewindResult {
  value: bigint
  blindingFactor: Buffer
  message: Buffer
}

/** Result of rewinding an AmountShielded output. */
export interface RewoundAmountShieldedOutput {
  value: bigint
  blindingFactor: Buffer
}

/** Result of rewinding a FullShielded output. */
export interface RewoundFullShieldedOutput {
  value: bigint
  blindingFactor: Buffer
  tokenUid: Buffer
  assetBlindingFactor: Buffer
}

export interface SurjectionDomainEntry {
  generator: Buffer
  tag: Buffer
  blindingFactor: Buffer
}

export interface TransparentEntry {
  amount: bigint
  tokenUid: Buffer
}

/** Validate that bytes represent a valid Pedersen commitment (curve point). */
export declare function validateCommitment(data: Buffer): boolean

/** Validate that bytes represent a valid generator (curve point). */
export declare function validateGenerator(data: Buffer): boolean

/**
 * Verify the homomorphic balance equation.
 *
 * `excess_blinding_factor` (optional, 32 bytes) supports full-unshield
 * transactions (`UnshieldBalanceHeader`, header id 0x13): shielded inputs with
 * no shielded outputs, where the sender reveals `excess = sum(r_in) − sum(r_out)`.
 * Matches hathor-core's signature so client-side verification covers the same
 * transaction classes the node accepts.
 */
export declare function verifyBalance(transparentInputs: Array<TransparentEntry>, shieldedInputs: Array<Buffer>, transparentOutputs: Array<TransparentEntry>, shieldedOutputs: Array<Buffer>, excessBlindingFactor?: Buffer | undefined | null): boolean

/** Verify that sum of positive commitments equals sum of negative commitments. */
export declare function verifyCommitmentsSum(positive: Array<Buffer>, negative: Array<Buffer>): boolean

/** Verify a Borromean range proof. */
export declare function verifyRangeProof(proof: Buffer, commitment: Buffer, generator: Buffer): boolean

/** Verify a surjection proof. */
export declare function verifySurjectionProof(proof: Buffer, codomain: Buffer, domain: Array<Buffer>): boolean
