// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (process.report && typeof process.report.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./ct-crypto.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hathor/ct-crypto-node-android-arm64')
        const bindingPackageVersion = require('@hathor/ct-crypto-node-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./ct-crypto.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hathor/ct-crypto-node-android-arm-eabi')
        const bindingPackageVersion = require('@hathor/ct-crypto-node-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if ((process.config && process.config.variables && process.config.variables.shlib_suffix === 'dll.a') || (process.config && process.config.variables && process.config.variables.node_target_type === 'shared_library')) {
        try {
        return require('./ct-crypto.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hathor/ct-crypto-node-win32-x64-gnu')
        const bindingPackageVersion = require('@hathor/ct-crypto-node-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./ct-crypto.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hathor/ct-crypto-node-win32-x64-msvc')
        const bindingPackageVersion = require('@hathor/ct-crypto-node-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./ct-crypto.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hathor/ct-crypto-node-win32-ia32-msvc')
        const bindingPackageVersion = require('@hathor/ct-crypto-node-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./ct-crypto.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hathor/ct-crypto-node-win32-arm64-msvc')
        const bindingPackageVersion = require('@hathor/ct-crypto-node-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./ct-crypto.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@hathor/ct-crypto-node-darwin-universal')
      const bindingPackageVersion = require('@hathor/ct-crypto-node-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./ct-crypto.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hathor/ct-crypto-node-darwin-x64')
        const bindingPackageVersion = require('@hathor/ct-crypto-node-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./ct-crypto.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hathor/ct-crypto-node-darwin-arm64')
        const bindingPackageVersion = require('@hathor/ct-crypto-node-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./ct-crypto.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hathor/ct-crypto-node-freebsd-x64')
        const bindingPackageVersion = require('@hathor/ct-crypto-node-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./ct-crypto.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hathor/ct-crypto-node-freebsd-arm64')
        const bindingPackageVersion = require('@hathor/ct-crypto-node-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./ct-crypto.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hathor/ct-crypto-node-linux-x64-musl')
          const bindingPackageVersion = require('@hathor/ct-crypto-node-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./ct-crypto.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hathor/ct-crypto-node-linux-x64-gnu')
          const bindingPackageVersion = require('@hathor/ct-crypto-node-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./ct-crypto.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hathor/ct-crypto-node-linux-arm64-musl')
          const bindingPackageVersion = require('@hathor/ct-crypto-node-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./ct-crypto.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hathor/ct-crypto-node-linux-arm64-gnu')
          const bindingPackageVersion = require('@hathor/ct-crypto-node-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./ct-crypto.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hathor/ct-crypto-node-linux-arm-musleabihf')
          const bindingPackageVersion = require('@hathor/ct-crypto-node-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./ct-crypto.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hathor/ct-crypto-node-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@hathor/ct-crypto-node-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./ct-crypto.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hathor/ct-crypto-node-linux-loong64-musl')
          const bindingPackageVersion = require('@hathor/ct-crypto-node-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./ct-crypto.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hathor/ct-crypto-node-linux-loong64-gnu')
          const bindingPackageVersion = require('@hathor/ct-crypto-node-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./ct-crypto.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hathor/ct-crypto-node-linux-riscv64-musl')
          const bindingPackageVersion = require('@hathor/ct-crypto-node-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./ct-crypto.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hathor/ct-crypto-node-linux-riscv64-gnu')
          const bindingPackageVersion = require('@hathor/ct-crypto-node-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./ct-crypto.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hathor/ct-crypto-node-linux-ppc64-gnu')
        const bindingPackageVersion = require('@hathor/ct-crypto-node-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./ct-crypto.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hathor/ct-crypto-node-linux-s390x-gnu')
        const bindingPackageVersion = require('@hathor/ct-crypto-node-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./ct-crypto.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hathor/ct-crypto-node-openharmony-arm64')
        const bindingPackageVersion = require('@hathor/ct-crypto-node-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./ct-crypto.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hathor/ct-crypto-node-openharmony-x64')
        const bindingPackageVersion = require('@hathor/ct-crypto-node-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./ct-crypto.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hathor/ct-crypto-node-openharmony-arm')
        const bindingPackageVersion = require('@hathor/ct-crypto-node-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.0.1-shielded' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.1-shielded but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value → native binding preferred, WASI is only a fallback
//   'true'                   → force WASI fallback even if native loaded
//   'error'                  → force WASI and throw if no WASI binding is found
// Treating any non-empty string as truthy (the historical behavior) meant
// NAPI_RS_FORCE_WASI=false, NAPI_RS_FORCE_WASI=0, etc. inadvertently triggered
// the WASI path, causing ENOENT for packages shipped without a .wasi.cjs file.
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === 'true' || process.env.NAPI_RS_FORCE_WASI === 'error'

if (!nativeBinding || forceWasi) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./ct-crypto.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (forceWasi) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || forceWasi) {
    try {
      wasiBinding = require('@hathor/ct-crypto-node-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (forceWasi) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const error = new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
    )
    // assign instead of the `new Error(message, { cause })` options form,
    // which Node < 16.9 silently ignores
    error.cause = loadErrors.reduce((err, cur) => {
      cur.cause = err
      return cur
    })
    throw error
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.computeBalancingBlindingFactor = nativeBinding.computeBalancingBlindingFactor
module.exports.createAmountShieldedOutput = nativeBinding.createAmountShieldedOutput
module.exports.createAssetCommitment = nativeBinding.createAssetCommitment
module.exports.createCommitment = nativeBinding.createCommitment
module.exports.createRangeProof = nativeBinding.createRangeProof
module.exports.createShieldedOutputWithBothBlindings = nativeBinding.createShieldedOutputWithBothBlindings
module.exports.createSurjectionProof = nativeBinding.createSurjectionProof
module.exports.createTrivialCommitment = nativeBinding.createTrivialCommitment
module.exports.deriveAssetTag = nativeBinding.deriveAssetTag
module.exports.deriveEcdhSharedSecret = nativeBinding.deriveEcdhSharedSecret
module.exports.deriveRewindNonce = nativeBinding.deriveRewindNonce
module.exports.deriveTag = nativeBinding.deriveTag
module.exports.generateEphemeralKeypair = nativeBinding.generateEphemeralKeypair
module.exports.generateRandomBlindingFactor = nativeBinding.generateRandomBlindingFactor
module.exports.getCommitmentSize = nativeBinding.getCommitmentSize
module.exports.getGeneratorSize = nativeBinding.getGeneratorSize
module.exports.getZeroTweak = nativeBinding.getZeroTweak
module.exports.htrAssetTag = nativeBinding.htrAssetTag
module.exports.rewindAmountShieldedOutput = nativeBinding.rewindAmountShieldedOutput
module.exports.rewindFullShieldedOutput = nativeBinding.rewindFullShieldedOutput
module.exports.rewindRangeProof = nativeBinding.rewindRangeProof
module.exports.validateCommitment = nativeBinding.validateCommitment
module.exports.validateGenerator = nativeBinding.validateGenerator
module.exports.verifyBalance = nativeBinding.verifyBalance
module.exports.verifyCommitmentsSum = nativeBinding.verifyCommitmentsSum
module.exports.verifyRangeProof = nativeBinding.verifyRangeProof
module.exports.verifySurjectionProof = nativeBinding.verifySurjectionProof
