#!/usr/bin/env bash
#
# Build the browser-compatible artifact for `@hathor/ct-crypto-wasm`.
# wasm-pack regenerates `pkg/package.json` from `Cargo.toml` on every
# build, but the package name we want (`@hathor/ct-crypto-wasm`) doesn't
# match the crate name on disk (`hathor-ct-crypto-wasm` — npm scope vs
# Cargo name); this script runs the build and then patches the
# regenerated package.json with the npm-scoped name plus a few
# bundler-friendly fields.
#
# Run inside the `nix develop` shell (or any environment where
# `wasm-pack` and an unwrapped clang with the wasm32 backend are on
# PATH; see `flake.nix` for the canonical setup).
#
# Usage:
#   ./scripts/build-wasm.sh

set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v wasm-pack >/dev/null 2>&1; then
  echo "error: wasm-pack not found on PATH. Enter the nix dev shell first: nix develop" >&2
  exit 1
fi

wasm-pack build --target web

# Copy the wallet-lib shielded crypto provider adapter + its types + the LICENSE
# into the published artifact. Sources live at repo root so they stay in git;
# pkg/ is regenerated by every wasm-pack run (everything
# the published package needs must be (re)written here, never hand-edited in
# pkg/, or the next build silently drops it).
cp provider.js pkg/
cp provider.d.ts pkg/
cp ../../LICENSE pkg/

# Post-process: scoped name + bundler-friendly fields + runtime deps. Without
# `module` CRA / webpack 5 won't tree-shake; without `sideEffects` listing the
# init JS the dynamic-import path that runs `wasm.default()` could be DCE'd;
# without `dependencies` the provider's `@hathor/ct-crypto-provider` and
# `buffer` imports fail to resolve in consumers.
PKG=pkg/package.json
node -e '
const fs = require("fs");
const p = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
// Single source of truth for the published version + runtime deps is the
// package dev manifest (./package.json), which the release bump updates.
// wasm-pack stamps the crate version from Cargo.toml into pkg/; override it
// here so a release only has to touch package.json, not Cargo.toml/Cargo.lock.
const src = JSON.parse(fs.readFileSync("package.json", "utf8"));
p.name = "@hathor/ct-crypto-wasm";
p.version = src.version;
p.module = "hathor_ct_crypto_wasm.js";
p.description = "Browser-compatible (wasm-bindgen) build of the Hathor confidential-transaction crypto primitives. Verifier-only: see @hathor/ct-crypto-node for the full Node surface.";
p.sideEffects = ["./hathor_ct_crypto_wasm.js", "./snippets/*", "./provider.js"];
p.license = "MIT";
// Pin the runtime deps that provider.js imports, taken from
// the dev manifest so provider/buffer pins stay in one place.
p.dependencies = Object.assign({}, p.dependencies, src.dependencies);
for (const f of ["hathor_ct_crypto_wasm_bg.wasm.d.ts", "provider.js", "provider.d.ts", "LICENSE"]) {
  if (!p.files.includes(f)) p.files.push(f);
}
// Subpath export so consumers can `import .. from "@hathor/ct-crypto-wasm/provider"`.
// Include a `types` condition so TS consumers get declarations.
p.exports = {
  ".": {
    "types": "./hathor_ct_crypto_wasm.d.ts",
    "default": "./hathor_ct_crypto_wasm.js"
  },
  "./provider": {
    "types": "./provider.d.ts",
    "default": "./provider.js"
  }
};
fs.writeFileSync(process.argv[1], JSON.stringify(p, null, 2) + "\n");
' "$PKG"

echo "[build-wasm] wrote $(pwd)/$PKG"
