#!/usr/bin/env bash
#
# Build the browser-compatible artifact for `@hathor/ct-crypto-wasm`.
# wasm-pack regenerates `pkg/package.json` from `Cargo.toml` on every
# build, but the package name we want (`@hathor/ct-crypto-wasm`) doesn't
# match the crate name on disk (`hathor-ct-crypto-wasm` — npm scope vs
# Cargo name); this script runs the build and then patches the
# regenerated package.json with the npm-scoped name plus a few
# bundler-friendly fields.
#
# Run inside the `nix develop` shell (or any environment where
# `wasm-pack` and an unwrapped clang with the wasm32 backend are on
# PATH; see `flake.nix` for the canonical setup).
#
# Usage:
#   ./scripts/build-wasm.sh

set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v wasm-pack >/dev/null 2>&1; then
  echo "error: wasm-pack not found on PATH. Enter the nix dev shell first: nix develop" >&2
  exit 1
fi

wasm-pack build --target web

# Copy the wallet-lib shielded crypto provider adapter into the published
# artifact. The source lives at repo root so it stays in git; pkg/ is
# regenerated by every wasm-pack run.
cp provider.js pkg/

# Post-process: scoped name + bundler-friendly fields. Without `module`
# CRA / webpack 5 won't tree-shake; without `sideEffects` listing the
# init JS the dynamic-import path that runs `wasm.default()` could be
# DCE'd.
PKG=pkg/package.json
node -e '
const fs = require("fs");
const p = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
p.name = "@hathor/ct-crypto-wasm";
p.module = "hathor_ct_crypto_wasm.js";
p.description = "Browser-compatible (wasm-bindgen) build of the Hathor confidential-transaction crypto primitives. Verifier-only: see @hathor/ct-crypto-node for the full Node surface.";
p.sideEffects = ["./hathor_ct_crypto_wasm.js", "./snippets/*", "./provider.js"];
if (!p.files.includes("hathor_ct_crypto_wasm_bg.wasm.d.ts")) {
  p.files.push("hathor_ct_crypto_wasm_bg.wasm.d.ts");
}
if (!p.files.includes("provider.js")) {
  p.files.push("provider.js");
}
// Subpath export so consumers can `import .. from "@hathor/ct-crypto-wasm/provider"`.
// Includes the main entry too so the original `main` / `module` fields
// remain effective alongside the new exports map.
p.exports = {
  ".": {
    "types": "./hathor_ct_crypto_wasm.d.ts",
    "default": "./hathor_ct_crypto_wasm.js"
  },
  "./provider": "./provider.js"
};
fs.writeFileSync(process.argv[1], JSON.stringify(p, null, 2) + "\n");
' "$PKG"

echo "[build-wasm] wrote $(pwd)/$PKG"
